"use client";

import { type Dispatch, type FormEvent, type SetStateAction, useMemo, useState } from "react";
import { Edit3, Filter, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import type { CurrencyRecord } from "./property-types";

const catalogue = [
  { code: "LKR", name: "Sri Lanka Rupees", symbol: "LKR" }, { code: "USD", name: "United States Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" }, { code: "GBP", name: "British Pound Sterling", symbol: "£" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" }, { code: "MVR", name: "Maldivian Rufiyaa", symbol: "MVR" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "SCR" }, { code: "INR", name: "Indian Rupee", symbol: "₹" }
];

export function CurrencyTab({ currencies, setCurrencies, manualRates, setManualRates, hotelCurrency, setToast }: { currencies: CurrencyRecord[]; setCurrencies: Dispatch<SetStateAction<CurrencyRecord[]>>; manualRates: boolean; setManualRates: Dispatch<SetStateAction<boolean>>; hotelCurrency: string; setToast: (message: string) => void }) {
  const [search, setSearch] = useState(""); const [filterOpen, setFilterOpen] = useState(false); const [drawer, setDrawer] = useState<CurrencyRecord | "new" | null>(null);
  const visible = useMemo(() => currencies.filter((item) => [item.code, item.name, item.symbol].join(" ").toLowerCase().includes(search.toLowerCase())), [currencies, search]);
  function refresh(id: string) { setCurrencies((items) => items.map((item) => item.id === id && !item.isDefault ? { ...item, hotelToCurrency: Number((item.hotelToCurrency * (0.995 + Math.random() * 0.01)).toFixed(6)) } : item)); setToast("Exchange rate refreshed for this session"); }
  return <div><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Currency</h2><button onClick={() => setDrawer("new")} className="inline-flex h-11 items-center gap-2 rounded-md bg-ink px-5 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Create Currency</button></div>
    <div className="mt-5 flex gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search..." className="focus-ring h-12 w-full rounded-md border border-line pl-11 pr-3" /></label><button onClick={() => setFilterOpen(!filterOpen)} className="inline-flex h-12 items-center gap-2 rounded-md border border-line px-5 font-semibold"><Filter className="h-4 w-4" />Filter</button></div>
    <div className="my-4 flex flex-wrap items-center gap-3 text-sm"><span className="text-slate-500">Hotel currency:</span><strong className="rounded-full bg-slate-100 px-3 py-1">{hotelCurrency}</strong><span className="rounded-full bg-slate-100 px-3 py-1 font-semibold">{manualRates ? "Manual exchange rates" : "Live exchange rates"}</span><label className="flex items-center gap-2"><input type="checkbox" checked={manualRates} onChange={(e) => setManualRates(e.target.checked)} />Manual exchange rates</label>{filterOpen ? <label className="ml-auto">Show <select className="ml-2 rounded border border-line p-2" onChange={(e) => setSearch(e.target.value)}><option value="">All</option><option value={hotelCurrency}>Hotel currency</option><option value="$">Dollar currencies</option></select></label> : null}</div>
    <section className="rounded-lg border border-line p-5"><h3 className="mb-5 text-2xl font-semibold">Currency</h3><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="border-b border-line text-slate-500">{["Code", "Name", "Symbol", "Hotel to Currency", "Currency to Hotel", "Default", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-b border-line"><td className="px-4 py-4 font-semibold">{item.code}</td><td className="px-4 py-4">{item.name}</td><td className="px-4 py-4">{item.symbol}</td><td className="px-4 py-4">1 {hotelCurrency} = {item.hotelToCurrency.toFixed(3)} {item.code}</td><td className="px-4 py-4">1 {item.code} = {(1 / item.hotelToCurrency).toFixed(3)} {hotelCurrency}</td><td className="px-4 py-4">{item.isDefault ? <span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-700">Yes</span> : "No"}</td><td className="px-4 py-4"><div className="flex gap-3"><button onClick={() => refresh(item.id)} title="Refresh"><RefreshCw className="h-4 w-4" /></button><button onClick={() => setDrawer(item)} title="Edit"><Edit3 className="h-4 w-4" /></button><button disabled={item.isDefault} onClick={() => setCurrencies((rows) => rows.filter((row) => row.id !== item.id))} title="Delete" className="text-rose-500 disabled:opacity-30"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></section>
    {drawer ? <CurrencyDrawer item={drawer === "new" ? null : drawer} hotelCurrency={hotelCurrency} onClose={() => setDrawer(null)} onSave={(saved) => { setCurrencies((items) => drawer === "new" ? [...items, saved] : items.map((item) => item.id === saved.id ? saved : item)); setDrawer(null); setToast(`Currency ${drawer === "new" ? "created" : "updated"}`); }} /> : null}
  </div>;
}

function CurrencyDrawer({ item, hotelCurrency, onClose, onSave }: { item: CurrencyRecord | null; hotelCurrency: string; onClose: () => void; onSave: (item: CurrencyRecord) => void }) {
  const [from, setFrom] = useState(hotelCurrency); const [to, setTo] = useState(item?.code ?? ""); const [name, setName] = useState(item?.name ?? ""); const [rate, setRate] = useState(String(item?.hotelToCurrency ?? ""));
  function chooseTo(code: string) { setTo(code); const found = catalogue.find((currency) => currency.code === code); if (!name && found) setName(found.name); }
  function submit(e: FormEvent) { e.preventDefault(); const found = catalogue.find((currency) => currency.code === to); if (!found) return; onSave({ id: item?.id ?? `${to}-${Date.now()}`, code: to, name: name || found.name, symbol: found.symbol, hotelToCurrency: Number(rate), isDefault: item?.isDefault ?? false }); }
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40"><aside className="h-full w-full max-w-[780px] rounded-l-2xl bg-white p-8 shadow-2xl"><header className="flex justify-between"><div><h2 className="text-2xl font-bold">{item ? "Edit" : "Add"} Currency</h2><p className="mt-3 text-slate-500">Select currencies and enter the exchange rate</p></div><button onClick={onClose}><X /></button></header><form onSubmit={submit} className="mt-7 space-y-5"><SelectField label="From Currency" value={from} onChange={setFrom} /><SelectField label="To Currency" value={to} onChange={chooseTo} /><Field label="Name" value={name} setValue={setName} /><Field label="Exchange Rate" value={rate} setValue={setRate} type="number" /><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="h-11 rounded-md border border-line px-5 font-semibold">Cancel</button><button className="h-11 rounded-md bg-ink px-5 font-semibold text-white">Save</button></div></form></aside></div>;
}
function SelectField({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label><span className="mb-2 block font-semibold">{label}</span><select required value={value} onChange={(e) => onChange(e.target.value)} className="focus-ring h-12 w-full rounded-md border border-line bg-white px-3"><option value="">Select currency</option>{catalogue.map((item) => <option key={item.code} value={item.code}>{item.code} — {item.name}</option>)}</select></label>; }
function Field({ label, value, setValue, type = "text" }: { label: string; value: string; setValue: (v: string) => void; type?: string }) { return <label><span className="mb-2 block font-semibold">{label}</span><input required min={type === "number" ? "0.000001" : undefined} step="any" type={type} value={value} onChange={(e) => setValue(e.target.value)} className="focus-ring h-12 w-full rounded-md border border-line px-3" /></label>; }
