"use client";

import { type Dispatch, type FormEvent, type SetStateAction, useState } from "react";
import type { MealAllocation } from "./property-types";

const empty = { breakfast: 0, lunch: 0, dinner: 0, currency: "LKR", allInclusive: false };
export function MealAllocationTab({ allocations, setAllocations, setToast }: { allocations: MealAllocation[]; setAllocations: Dispatch<SetStateAction<MealAllocation[]>>; setToast: (message: string) => void }) {
  const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState<string | null>(null);
  function submit(event: FormEvent) { event.preventDefault(); if (editingId) setAllocations((items) => items.map((item) => item.id === editingId ? { ...form, id: item.id } : item)); else setAllocations((items) => [...items, { ...form, id: `meal-${Date.now()}` }]); setForm(empty); setEditingId(null); setToast(editingId ? "Meal allocation updated" : "Meal allocation created"); }
  function edit(item: MealAllocation) { setForm({ breakfast: item.breakfast, lunch: item.lunch, dinner: item.dinner, currency: item.currency, allInclusive: item.allInclusive }); setEditingId(item.id); }
  return <div><h2 className="text-xl font-semibold">Meal Allocation</h2><p className="mt-1 text-sm text-slate-500">Set the number of included meals per day and whether the plan is All-Inclusive.</p><div className="mt-6 grid gap-6 lg:grid-cols-[520px_1fr]">
    <form onSubmit={submit} className="rounded-lg border border-line p-6"><h3 className="mb-6 text-lg font-semibold">{editingId ? "Edit Allocation" : "Create Allocation"}</h3><div className="grid grid-cols-3 gap-3">{(["breakfast", "lunch", "dinner"] as const).map((key) => <label key={key}><span className="mb-2 block font-semibold capitalize">{key}</span><input min="0" type="number" value={form[key]} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} className="focus-ring h-12 w-full rounded-md border border-line px-3" /></label>)}</div><div className="mt-5 flex flex-wrap items-end gap-5"><label className="min-w-52"><span className="mb-2 block font-semibold">Currency</span><select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })} className="focus-ring h-12 w-full rounded-md border border-line bg-white px-3"><option>LKR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label className="flex h-12 items-center gap-3 font-semibold">All-Inclusive<input type="checkbox" checked={form.allInclusive} onChange={(e) => setForm({ ...form, allInclusive: e.target.checked })} className="h-5 w-5 accent-ink" /></label></div><button className="mt-6 h-11 rounded-md bg-ink px-5 font-semibold text-white">{editingId ? "Save" : "Create"}</button></form>
    <section className="rounded-lg border border-line p-6"><h3 className="mb-6 text-lg font-semibold">Existing Allocations</h3>{allocations.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-line text-slate-500">{["Breakfast", "Lunch", "Dinner", "All-Inclusive", "Currency", "Actions"].map((h) => <th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{allocations.map((item) => <tr key={item.id} className="border-b border-line"><td className="px-3 py-4">{item.breakfast}</td><td className="px-3 py-4">{item.lunch}</td><td className="px-3 py-4">{item.dinner}</td><td className="px-3 py-4">{item.allInclusive ? "Yes" : "No"}</td><td className="px-3 py-4">{item.currency}</td><td className="px-3 py-4"><div className="flex gap-2"><button onClick={() => edit(item)} className="rounded-md border border-line px-3 py-2 font-semibold">Edit</button><button onClick={() => setAllocations((current) => current.filter((row) => row.id !== item.id))} className="rounded-md bg-rose-500 px-3 py-2 font-semibold text-white">Delete</button></div></td></tr>)}</tbody></table></div> : <p className="text-slate-500">No allocations yet.</p>}</section>
  </div></div>;
}
