"use client";
import { type Dispatch, type FormEvent, type SetStateAction, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import type { TaxRecord } from "./property-types";

export function TaxesTab({ taxes, setTaxes, setToast }: { taxes: TaxRecord[]; setTaxes: Dispatch<SetStateAction<TaxRecord[]>>; setToast: (message: string) => void }) {
  const [name, setName] = useState(""); const [rate, setRate] = useState(""); const [inclusive, setInclusive] = useState(false);
  function submit(e: FormEvent) { e.preventDefault(); setTaxes((items) => [...items, { id: `tax-${Date.now()}`, name, rate: Number(rate), inclusive, active: true }]); setName(""); setRate(""); setInclusive(false); setToast("Tax rule created"); }
  return <div><h2 className="text-2xl font-semibold">Taxes</h2><p className="mt-1 text-sm text-slate-500">Create and manage property tax rules for future Supabase integration.</p><div className="mt-6 grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-lg border border-line p-5"><h3 className="font-semibold">Create Tax</h3><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Tax name" className="focus-ring h-11 w-full rounded-md border border-line px-3" /><input required min="0" step="0.01" type="number" value={rate} onChange={(e) => setRate(e.target.value)} placeholder="Rate %" className="focus-ring h-11 w-full rounded-md border border-line px-3" /><label className="flex gap-2"><input type="checkbox" checked={inclusive} onChange={(e) => setInclusive(e.target.checked)} />Included in displayed prices</label><button className="inline-flex h-11 items-center gap-2 rounded-md bg-ink px-4 font-semibold text-white"><Plus className="h-4 w-4" />Create</button></form><section className="rounded-lg border border-line p-5"><h3 className="mb-4 font-semibold">Tax Rules</h3>{taxes.length ? <div className="space-y-3">{taxes.map((tax) => <div key={tax.id} className="flex items-center justify-between rounded-md border border-line p-4"><div><p className="font-semibold">{tax.name} · {tax.rate}%</p><p className="text-sm text-slate-500">{tax.inclusive ? "Inclusive" : "Added at checkout"}</p></div><div className="flex items-center gap-3"><input type="checkbox" checked={tax.active} onChange={(e) => setTaxes((items) => items.map((item) => item.id === tax.id ? { ...item, active: e.target.checked } : item))} /><button onClick={() => setTaxes((items) => items.filter((item) => item.id !== tax.id))} className="text-rose-500"><Trash2 className="h-4 w-4" /></button></div></div>)}</div> : <p className="text-slate-500">No tax rules yet.</p>}</section></div></div>;
}
