"use client";
import { type Dispatch, type SetStateAction, useEffect, useState } from "react";
import { Moon, Palette, RotateCcw, Sun } from "lucide-react";
import type { ThemeSettings } from "./property-types";

const accents = [{ name: "Blue", color: "#3b82f6" }, { name: "Green", color: "#22c55e" }, { name: "Purple", color: "#a855f7" }, { name: "Red", color: "#ef4444" }, { name: "Orange", color: "#f97316" }, { name: "Pink", color: "#ec4899" }];
const descriptions: Record<string, string> = { "Confirmed Reservation": "Confirmed bookings", Tentative: "Tentative reservations", "Checked-out": "Guests who have checked out", "Checked-in": "Guests currently checked in", Cancelled: "Cancelled reservations", "No Show": "Guests who didn't show up", "No-Show (Surcharge)": "No-show with surcharge applied", Block: "Blocked rooms", "OUT OF ORDER": "Rooms out of order", InvalidCC: "Invalid credit card" };

export function ThemeTab({ value, setValue, defaults, setToast }: { value: ThemeSettings; setValue: Dispatch<SetStateAction<ThemeSettings>>; defaults: ThemeSettings; setToast: (message: string) => void }) {
  const [draftColors, setDraftColors] = useState(value.statusColors);
  useEffect(() => { document.documentElement.dataset.themeMode = value.mode; document.documentElement.style.setProperty("--property-accent", value.accent); }, [value.accent, value.mode]);
  const dark = value.mode === "dark";
  return <div className="space-y-7"><h2 className="flex items-center gap-2 text-2xl font-semibold"><Palette />Theme Settings</h2>
    <Section title="Theme Mode" subtitle="Choose your preferred theme mode for the application"><label className="mb-4 flex gap-2"><input type="checkbox" checked={value.autoDetect} onChange={(e) => setValue({ ...value, autoDetect: e.target.checked, mode: e.target.checked ? "system" : value.mode })} />Auto-detect system theme</label><div className="space-y-2">{(["light", "dark", "system"] as const).map((mode) => <label key={mode} className="flex items-center gap-2 capitalize"><input type="radio" checked={value.mode === mode} onChange={() => setValue({ ...value, mode, autoDetect: mode === "system" })} />{mode === "light" ? <Sun className="h-4 w-4" /> : mode === "dark" ? <Moon className="h-4 w-4" /> : null}{mode} Mode</label>)}</div></Section>
    <Section title="Accent Color" subtitle="Choose your preferred accent color for buttons and highlights"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{accents.map((accent) => <button key={accent.name} onClick={() => setValue({ ...value, accent: accent.color })} className={`flex h-14 items-center gap-3 rounded-md border-2 px-4 font-semibold ${value.accent === accent.color ? "border-current" : "border-line"}`} style={{ color: value.accent === accent.color ? accent.color : undefined }}><span className="h-7 w-7 rounded-full" style={{ background: accent.color }} />{accent.name}</button>)}</div></Section>
    <Section title="Preview" subtitle="See how your theme settings look"><div className={`rounded-lg border p-5 ${dark ? "border-slate-700 bg-slate-900 text-white" : "border-line bg-white"}`}><div className="flex justify-between"><h3 className="text-lg font-semibold">Sample Content</h3><button className="rounded-md px-4 py-2 font-semibold text-white" style={{ background: value.accent }}>Sample Button</button></div><p className="my-5 text-slate-500">This is how your content will appear with the selected theme settings.</p><div className="flex gap-2"><button className="rounded px-4 py-2 text-white" style={{ background: value.accent }}>Primary</button><button className="rounded border border-line px-4 py-2">Secondary</button><button className="px-4 py-2">Ghost</button></div></div></Section>
    <Section title="Reservation Status Colors" subtitle="Customize colors for different reservation statuses"><div className="space-y-3">{Object.entries(draftColors).map(([status, color]) => <div key={status} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line p-4"><div className="flex items-center gap-3"><span className="h-5 w-5 rounded-full" style={{ background: color }} /><div><p className="font-semibold">{status}</p><p className="text-sm text-slate-500">{descriptions[status]}</p></div></div><div className="flex items-center gap-2"><input type="color" value={color} onChange={(e) => setDraftColors({ ...draftColors, [status]: e.target.value })} className="h-10 w-14" /><input value={color} onChange={(e) => setDraftColors({ ...draftColors, [status]: e.target.value })} className="h-10 w-28 rounded border border-line px-2 font-mono text-sm" /></div></div>)}</div><div className="mt-5 flex flex-wrap gap-2 rounded-lg bg-slate-50 p-4">{Object.entries(draftColors).map(([status, color]) => <span key={status} className="rounded px-3 py-1 text-sm font-semibold text-white" style={{ background: color }}>{status}</span>)}</div><div className="mt-5 flex gap-3"><button onClick={() => { setValue({ ...value, statusColors: draftColors }); setToast("Reservation status colors saved"); }} className="h-11 rounded-md px-5 font-semibold text-white" style={{ background: value.accent }}>Save Colors</button><button onClick={() => setDraftColors(value.statusColors)} className="inline-flex h-11 items-center gap-2 rounded-md border border-line px-5 font-semibold"><RotateCcw className="h-4 w-4" />Reset</button></div></Section>
    <Section title="Reset Theme" subtitle="Reset all theme settings to default values"><button onClick={() => { setValue(defaults); setDraftColors(defaults.statusColors); setToast("Theme reset to default"); }} className="rounded-md border border-line px-5 py-3 font-semibold">Reset to Default</button></Section>
  </div>;
}
function Section({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-lg border border-line p-6"><h3 className="text-2xl font-semibold">{title}</h3><p className="mb-6 mt-1 text-slate-500">{subtitle}</p>{children}</section>; }
